# PID of current job: 3004955
mSet<-InitDataObjects("conc", "msetora", FALSE, 150)
cmpd.vec<-c("Ac-Orn","ADMA","Ala","alpha-AAA","Arg","Asn","Asp","C0","C10","C10:1","C10:2","C12","C12:1","C12-DC","C14","C14:1","C14:1-OH","C14:2","C14:2-OH","C16","C16:1","C16:1-OH","C16:2","C16:2-OH","C16-OH","C18","C18:1","C18:2","C2","C3","C3-DC (C4-OH)","C3-OH","C4","C4:1","C5","C5:1","C5:1-DC","C5-DC (C6-OH)","C5-M-DC","C5-OH (C3-DC-M)","C6 (C4:1-DC)","C6:1","C7-DC","C8","C9","Cit","Creatinine","Gln","Glu","Gly","H1","His","Ile","Kynurenine","Leu","Lys","lysoPC a C14:0","lysoPC a C16:0","lysoPC a C16:1","lysoPC a C17:0","lysoPC a C18:0","lysoPC a C18:1","lysoPC a C18:2","lysoPC a C20:3","lysoPC a C20:4","lysoPC a C24:0","lysoPC a C26:0","lysoPC a C26:1","lysoPC a C28:0","lysoPC a C28:1","Met","Met-SO","Orn","PC aa C24:0","PC aa C28:1","PC aa C30:0","PC aa C30:2","PC aa C32:0","PC aa C32:1","PC aa C32:2","PC aa C32:3","PC aa C34:1","PC aa C34:2","PC aa C34:3","PC aa C34:4","PC aa C36:0","PC aa C36:1","PC aa C36:2","PC aa C36:3","PC aa C36:4","PC aa C36:5","PC aa C36:6","PC aa C38:0","PC aa C38:1","PC aa C38:3","PC aa C38:4","PC aa C38:5","PC aa C38:6","PC aa C40:1","PC aa C40:2","PC aa C40:3","PC aa C40:4","PC aa C40:5","PC aa C40:6","PC aa C42:0","PC aa C42:1","PC aa C42:2","PC aa C42:4","PC aa C42:5","PC aa C42:6","PC ae C30:0","PC ae C30:1","PC ae C30:2","PC ae C32:1","PC ae C32:2","PC ae C34:0","PC ae C34:1","PC ae C34:2","PC ae C34:3","PC ae C36:0","PC ae C36:1","PC ae C36:2","PC ae C36:3","PC ae C36:4","PC ae C36:5","PC ae C38:0","PC ae C38:1","PC ae C38:2","PC ae C38:3","PC ae C38:4","PC ae C38:5","PC ae C38:6","PC ae C40:1","PC ae C40:2","PC ae C40:3","PC ae C40:4","PC ae C40:5","PC ae C40:6","PC ae C42:0","PC ae C42:1","PC ae C42:2","PC ae C42:3","PC ae C42:4","PC ae C42:5","PC ae C44:3","PC ae C44:4","PC ae C44:5","PC ae C44:6","Phe","Pro","Putrescine","SDMA","Ser","Serotonin","SM (OH) C14:1","SM (OH) C16:1","SM (OH) C22:1","SM (OH) C22:2","SM (OH) C24:1","SM C16:0","SM C16:1","SM C18:0","SM C18:1","SM C20:2","SM C24:0","SM C24:1","SM C26:0","SM C26:1","Spermidine","Spermine","t4-OH-Pro","Taurine","Thr","total DMA","Trp","Tyr","Val")
mSet<-Setup.MapData(mSet, cmpd.vec);
mSet<-CrossReferencing(mSet, "name");
mSet<-CreateMappingResultTable(mSet)
mSet<-PerformDetailMatch(mSet, "Ac-Orn");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "Ac-Orn", "cis-Aconitic acid");
mSet<-PerformDetailMatch(mSet, "alpha-AAA");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "alpha-AAA", "Phenylalanine");
mSet<-PerformDetailMatch(mSet, "C0");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C0", "NC043");
mSet<-PerformDetailMatch(mSet, "C10");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C10", "Decanoyl-CoA (n-C10:0CoA)");
mSet<-PerformDetailMatch(mSet, "C10:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C10:1", "trans-Dec-2-enoic acid");
mSet<-PerformDetailMatch(mSet, "C12");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C12", "Dodecanoylcarnitine");
mSet<-PerformDetailMatch(mSet, "C10:2");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C10:2", "trans-Dec-2-enoic acid");
mSet<-PerformDetailMatch(mSet, "C12:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C12:1", "trans-Dodec-2-enoic acid");
mSet<-PerformDetailMatch(mSet, "C12-DC");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C12-DC", "Cer(d18:1/12:0)");
mSet<-PerformDetailMatch(mSet, "C14:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C14:1", "5-Tetradecenoic acid");
mSet<-PerformDetailMatch(mSet, "C14:1-OH");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C14:1-OH", "Hydroxysphingomyeline C14:1");
mSet<-PerformDetailMatch(mSet, "C14:2");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C14:2", "Linoleyl carnitine");
mSet<-PerformDetailMatch(mSet, "C14:2-OH");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C14:2-OH", "Hydroxysphingomyeline C14:1");
mSet<-PerformDetailMatch(mSet, "C16:1-OH");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C16:1-OH", "Hydroxysphingomyeline C16:1");
mSet<-PerformDetailMatch(mSet, "C16:2");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C16:2-OH");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C16-OH");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C16:2");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C18");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C18", "Stearoylcarnitine");
mSet<-PerformDetailMatch(mSet, "C18:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C18:1", "Cer(d18:1/18:1(9Z))");
mSet<-PerformDetailMatch(mSet, "C18:2");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C18:2", "Linoleyl carnitine");
mSet<-PerformDetailMatch(mSet, "C2");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C2", "L-Acetylcarnitine");
mSet<-PerformDetailMatch(mSet, "C3");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C3", "Propionylcarnitine");
mSet<-PerformDetailMatch(mSet, "C3-DC (C4-OH)");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C3-OH");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C4");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C4:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C5");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C5", "Valerylcarnitine");
mSet<-PerformDetailMatch(mSet, "C5:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C5:1", "(2E)-Piperamide-C5:1");
mSet<-PerformDetailMatch(mSet, "C5:1-DC");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C5-DC (C6-OH)");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C5-M-DC");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C6 (C4:1-DC)");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C6:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "C7-DC");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C7-DC", "3,3-Dichloro-4-(dichloromethylene)-2,5-pyrrolidinedione");
mSet<-PerformDetailMatch(mSet, "C8");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "C8", "Octanoylcarnitine");
mSet<-PerformDetailMatch(mSet, "C9");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "Gln");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "H1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "lysoPC a C14:0");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "lysoPC a C14:0", "LysoPC(18:1/0:0)");
mSet<-PerformDetailMatch(mSet, "lysoPC a C18:2");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "lysoPC a C18:2", "LysoPC(18:1/0:0)");
mSet<-PerformDetailMatch(mSet, "Met-SO");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "Orn");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "Orn", "Ornithine");
mSet<-PerformDetailMatch(mSet, "PC aa C24:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "PC aa C28:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "PC aa C30:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "PC aa C30:2");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "PC aa C32:3");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "PC aa C40:5");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM (OH) C14:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM (OH) C16:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM (OH) C22:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM (OH) C22:2");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM (OH) C24:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C16:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C18:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C18:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C20:2");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C24:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C24:1");
mSet<-GetCandidateList(mSet);
mSet<-SetCandidate(mSet, "SM C24:1", "Hydroxysphingomyeline C24:1");
mSet<-PerformDetailMatch(mSet, "SM C26:0");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "SM C26:1");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "t4-OH-Pro");
mSet<-GetCandidateList(mSet);
mSet<-PerformDetailMatch(mSet, "total DMA");
mSet<-GetCandidateList(mSet);
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-SetCurrentMsetLib(mSet, "RaMP_pathway", 2);
mSet<-CalculateHyperScore(mSet)
mSet<-PlotORA(mSet, "ora_0_", "net", "png", 150, width=NA)
mSet<-PlotEnrichDotPlot(mSet, "ora", "ora_dot_0_", "png", 150, width=NA)
mSet<-CalculateHyperScore(mSet)
mSet<-PlotORA(mSet, "ora_1_", "net", "png", 150, width=NA)
mSet<-PlotEnrichDotPlot(mSet, "ora", "ora_dot_1_", "png", 150, width=NA)
mSet<-SaveTransformedData(mSet)
